---
apiVersion: v1
kind: Namespace
metadata:
  name: otel-test
---
apiVersion: otel.stack.io/v1alpha1
kind : OpenTelemetryStack
metadata:
  name: stack-example
  namespace : otel-test
spec:
  gateway:
    enabled: true
    image:
      # image: busybox
      # tag: 1.37.0
      registry: docker.io
      repo : alex7285
      image : otel-gateway
      tag : dev@sha256:babc7ab4702915859b95cca0e5dd64d1e0e01735d3069ca82ef6b662f71d8aa5
    grpcDebugLogging : true