include: [ {{ .AuditLogPath }} ]
storage: {{ .StorageId }}
include_file_path: false
include_file_name: false
operators:
    - type: json_parser
      id: parse-body
      timestamp:
        parse_from: attributes.stageTimestamp
        layout: '%Y-%m-%dT%H:%M:%S.%LZ'
    - type: add
      field: attributes.log_type
      value: auditlog
    - type: add
      field: attributes.kubernetes_component
      value: kubeauditlogs
    - type: move
      from: attributes.stage
      to: resource["k8s.auditlog.stage"]
    - type: move
      from: attributes.stageTimestamp
      to: resource["k8s.auditlog.stage_timestamp"]
    - type: move
      from: attributes.level
      to: resource["k8s.auditlog.level"]
    - type: move
      from: attributes.auditID
      to: resource["k8s.auditlog.audit_id"]
    - type: move
      from: attributes.objectRef.resource
      to: resource["k8s.auditlog.resource"]
    - type: retain
      fields:
        - attributes.stage
        - attributes.stageTimestamp
        - attributes.level
        - attributes.auditID
        - attributes.objectRef.resource
        - attributes.cluster_id
        - attributes.time
        - attributes.log
        - attributes.log_type