include: [ /var/log/pods/*/*/*.log ]
exclude: []
storage: file_storage
include_file_path: true
include_file_name: false
operators:
# FInd out which format is used by kubernetes
- type: router
  id: get-format
  routes:
  - output: parser-docker
    expr: 'body matches "^\\{"'
  - output: parser-crio
    expr: 'body matches "^[^ Z]+ "'
  - output: parser-containerd
    expr: 'body matches "^[^ Z]+Z"'
    # Parse CRI-O format
- type: regex_parser
  id: parser-crio
  regex: '^(?P<time>[^ Z]+) (?P<stream>stdout|stderr) (?P<logtag>[^ ]*) ?(?P<log>.*)$'
  output: extract_metadata_from_filepath
  timestamp:
    parse_from: attributes.time
    layout_type: gotime
    layout: '2006-01-02T15:04:05.000000000-07:00'
  # Parse CRI-Containerd format
- type: regex_parser
  id: parser-containerd
  regex: '^(?P<time>[^ ^Z]+Z) (?P<stream>stdout|stderr) (?P<logtag>[^ ]*) ?(?P<log>.*)$'
  output: extract_metadata_from_filepath
  timestamp:
    parse_from: attributes.time
    layout: '%Y-%m-%dT%H:%M:%S.%LZ'
  # Parse Docker format
- type: json_parser
  id: parser-docker
  output: extract_metadata_from_filepath
  timestamp:
    parse_from: attributes.time
    layout: '%Y-%m-%dT%H:%M:%S.%LZ'
  # Extract metadata from file path
- type: regex_parser
  id: extract_metadata_from_filepath
  regex: '^.*\/(?P<namespace>[^_]+)_(?P<pod_name>[^_]+)_((?P<confighash>[a-f0-9]{32})|(?P<uid>[0-9a-f]{8}\b-[0-9a-f]{4}\b-[0-9a-f]{4}\b-[0-9a-f]{4}\b-[0-9a-f]{12}))\/(?P<container_name>[^\._]+)\/(?P<restart_count>\d+)\.log$'
  parse_from: attributes["log.file.path"]
- type: remove
  field: attributes["log.file.path"]
# Move out attributes to Attributes
- type: move
  id: move-namespace
  from: attributes.namespace
  to: resource["k8s.namespace.name"]
- type: move
  id: move-pod-name
  from: attributes.pod_name
  to: resource["k8s.pod.name"]
- type: move
  id: move-container-name
  from: attributes.container_name
  to: resource["k8s.container.name"]
- type: move
  from: attributes.uid
  to: resource["k8s.pod.uid"]
- type: move
  from: attributes.confighash
  to: resource["k8s.pod.confighash"]
