---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opentelemetry-collector-config
data:
  key: value

---
apiVersion: apps/v1
kind: Daemonset
metadata:
  name: open-telemetry-daemonset
spec:
  selector:
    matchLabels:
      app: otel-daemon
  template:
    metadata:
      labels:
        app: otel-daemon
    spec:
      containers:
      - name: collector
        image: ghcr.io/rancher-sandbox/logging-collector:v0.0.1 
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5601
---
