apiVersion: audit.k8s.io/v1
kind: Policy
rules:
  # Log all write requests at the RequestResponse level (includes request & response body)
  - level: RequestResponse
    verbs: ["create", "update", "patch", "delete", "deletecollection"]
    resources:
    - group: ""
      resources: ["pods", "services", "configmaps", "secrets"]
    - group: "apps"
      resources: ["deployments", "statefulsets", "daemonsets"]
  
  # Log all other requests at the Metadata level
  - level: Metadata