// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("k8sevent")
	ScopeName = "github.com/rancher-sandbox/ob-team-opentelemetry-poc/collector/receiver/k8seventreceiver"
)

const (
	LogsStability = component.StabilityLevelAlpha
)
