// Code generated by "go.opentelemetry.io/collector/cmd/builder". DO NOT EDIT.

// Program rancher-gateway-minimal is an OpenTelemetry Collector binary.
package main

import (
	"log"

	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/confmap"
	filereloader "github.com/rancher-sandbox/ob-team-opentelemetry-poc/collector/provider/filereloader"
	fileprovider "go.opentelemetry.io/collector/confmap/provider/fileprovider"
	envprovider "go.opentelemetry.io/collector/confmap/provider/envprovider"
	"go.opentelemetry.io/collector/otelcol"
)

func main() {
	info := component.BuildInfo{
		Command:     "rancher-gateway-minimal",
		Description: "(Minimal) OpenTelemetry Collector for Rancher Logging",
		Version:     "0.1.0+up0.125.0",
	}

	set := otelcol.CollectorSettings{
		BuildInfo: info,
		Factories: components,
		ConfigProviderSettings: otelcol.ConfigProviderSettings{
			ResolverSettings: confmap.ResolverSettings{
				ProviderFactories: []confmap.ProviderFactory{
					filereloader.NewFactory(),
					fileprovider.NewFactory(),
					envprovider.NewFactory(),
				},
			},
		},
		ProviderModules: map[string]string{
			filereloader.NewFactory().Create(confmap.ProviderSettings{}).Scheme(): "github.com/rancher-sandbox/ob-team-opentelemetry-poc/collector/provider/filereloader v0.125.0",
			fileprovider.NewFactory().Create(confmap.ProviderSettings{}).Scheme(): "go.opentelemetry.io/collector/confmap/provider/fileprovider v0.125.0",
			envprovider.NewFactory().Create(confmap.ProviderSettings{}).Scheme(): "go.opentelemetry.io/collector/confmap/provider/envprovider v1.25.0",
    	},
		ConverterModules: []string{
		},
	}

	if err := run(set); err != nil {
		log.Fatal(err)
	}
}

func runInteractive(params otelcol.CollectorSettings) error {
	cmd := otelcol.NewCommand(params)
	if err := cmd.Execute(); err != nil {
		log.Fatalf("collector server run finished with error: %v", err)
	}

	return nil
}
